"""Update Borrow record table V02

Revision ID: 2987bc8160a7
Revises: 5dc9a69e2087
Create Date: 2025-10-21 13:25:38.885642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2987bc8160a7'
down_revision: Union[str, None] = '5dc9a69e2087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
