"""Initialized DB

Revision ID: 2af17d5b7d36
Revises: 
Create Date: 2025-10-20 13:34:43.966792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af17d5b7d36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_title')
    )
    op.create_table('settings',
    sa.Column('setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('borrow_day_limit', sa.Integer(), nullable=False),
    sa.Column('borrow_day_extension_limit', sa.Integer(), nullable=False),
    sa.Column('borrow_max_limit', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('setting_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=150), nullable=False),
    sa.Column('user_photo', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users', ['user_email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_title', sa.String(length=200), nullable=False),
    sa.Column('book_author', sa.String(length=150), nullable=False),
    sa.Column('book_category_id', sa.Integer(), nullable=True),
    sa.Column('book_rating', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('book_photo', sa.String(), nullable=True),
    sa.Column('book_pdf', sa.String(), nullable=True),
    sa.Column('book_audio', sa.String(), nullable=True),
    sa.Column('book_details', sa.String(), nullable=True),
    sa.Column('book_availability', sa.Boolean(), nullable=True),
    sa.Column('book_count', sa.Integer(), nullable=True),
    sa.Column('book_review_count', sa.Integer(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['book_category_id'], ['categories.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('donation_books',
    sa.Column('d_book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_title', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_title', sa.String(length=200), nullable=False),
    sa.Column('book_author', sa.String(length=150), nullable=False),
    sa.Column('BS_mail', sa.String(length=150), nullable=False),
    sa.Column('BS_ID', sa.String(length=100), nullable=False),
    sa.Column('book_detail', sa.String(), nullable=True),
    sa.Column('book_photo', sa.String(), nullable=True),
    sa.Column('book_pdf', sa.String(), nullable=True),
    sa.Column('book_audio', sa.String(), nullable=True),
    sa.Column('book_count', sa.Integer(), nullable=True),
    sa.Column('book_approve', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('d_book_id')
    )
    op.create_table('book_reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('borrow_records',
    sa.Column('borrow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('borrow_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('borrow_status', sa.String(length=50), nullable=True),
    sa.Column('request_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('borrow_id')
    )
    op.create_table('user_rating',
    sa.Column('rating_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.DECIMAL(precision=2, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rating_id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uix_user_book')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rating')
    op.drop_table('borrow_records')
    op.drop_table('book_reviews')
    op.drop_table('donation_books')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('categories')
    # ### end Alembic commands ###
