"""Initial migration

Revision ID: 353bedcac6fa
Revises: 
Create Date: 2025-10-20 12:52:41.808733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353bedcac6fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(), nullable=False),
    sa.Column('book_category', sa.String(), nullable=False),
    sa.Column('book_author', sa.String(), nullable=False),
    sa.Column('book_description', sa.Text(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('available_copies', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('availabity_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_books_book_author'), 'books', ['book_author'], unique=False)
    op.create_index(op.f('ix_books_book_category'), 'books', ['book_category'], unique=False)
    op.create_index(op.f('ix_books_book_id'), 'books', ['book_id'], unique=False)
    op.create_index(op.f('ix_books_book_title'), 'books', ['book_title'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_book_title'), table_name='books')
    op.drop_index(op.f('ix_books_book_id'), table_name='books')
    op.drop_index(op.f('ix_books_book_category'), table_name='books')
    op.drop_index(op.f('ix_books_book_author'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
