"""Add Donation Table

Revision ID: 370a3d6ac3cb
Revises: ee1624afc989
Create Date: 2025-10-20 13:28:44.608866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370a3d6ac3cb'
down_revision: Union[str, None] = 'ee1624afc989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
