"""Add Donation Table

Revision ID: 729637185d87
Revises: 370a3d6ac3cb
Create Date: 2025-10-20 13:32:43.505027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729637185d87'
down_revision: Union[str, None] = '370a3d6ac3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_books',
    sa.Column('donation_book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(), nullable=False),
    sa.Column('book_author', sa.String(), nullable=False),
    sa.Column('donor_name', sa.String(), nullable=False),
    sa.Column('book_category', sa.String(), nullable=False),
    sa.Column('book_description', sa.Text(), nullable=True),
    sa.Column('BS_email', sa.String(), nullable=False),
    sa.Column('BS_ID', sa.String(), nullable=False),
    sa.Column('book_image', sa.String(), nullable=True),
    sa.Column('book_audio', sa.String(), nullable=True),
    sa.Column('book_pdf', sa.String(), nullable=True),
    sa.Column('donation_status', sa.String(), nullable=True),
    sa.Column('book_copies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('donation_book_id')
    )
    op.create_index(op.f('ix_donation_books_BS_ID'), 'donation_books', ['BS_ID'], unique=False)
    op.create_index(op.f('ix_donation_books_BS_email'), 'donation_books', ['BS_email'], unique=False)
    op.create_index(op.f('ix_donation_books_book_author'), 'donation_books', ['book_author'], unique=False)
    op.create_index(op.f('ix_donation_books_book_category'), 'donation_books', ['book_category'], unique=False)
    op.create_index(op.f('ix_donation_books_book_title'), 'donation_books', ['book_title'], unique=False)
    op.create_index(op.f('ix_donation_books_donation_book_id'), 'donation_books', ['donation_book_id'], unique=False)
    op.create_index(op.f('ix_donation_books_donor_name'), 'donation_books', ['donor_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donation_books_donor_name'), table_name='donation_books')
    op.drop_index(op.f('ix_donation_books_donation_book_id'), table_name='donation_books')
    op.drop_index(op.f('ix_donation_books_book_title'), table_name='donation_books')
    op.drop_index(op.f('ix_donation_books_book_category'), table_name='donation_books')
    op.drop_index(op.f('ix_donation_books_book_author'), table_name='donation_books')
    op.drop_index(op.f('ix_donation_books_BS_email'), table_name='donation_books')
    op.drop_index(op.f('ix_donation_books_BS_ID'), table_name='donation_books')
    op.drop_table('donation_books')
    # ### end Alembic commands ###
