"""Merge table head v02

Revision ID: ea562f4ebc14
Revises: 2c8b0ca12705
Create Date: 2025-10-22 15:02:36.234587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea562f4ebc14'
down_revision: Union[str, None] = '2c8b0ca12705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_records', sa.Column('returned_at', sa.Date(), nullable=True))
    op.drop_column('borrow_records', 'request_status')
    op.add_column('settings', sa.Column('booking_duration', sa.Integer(), nullable=False))
    op.add_column('settings', sa.Column('booking_days_limit', sa.Integer(), nullable=False))
    op.drop_column('settings', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('settings', 'booking_days_limit')
    op.drop_column('settings', 'booking_duration')
    op.add_column('borrow_records', sa.Column('request_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('borrow_records', 'returned_at')
    # ### end Alembic commands ###
