"""Update book table

Revision ID: ee1624afc989
Revises: 353bedcac6fa
Create Date: 2025-10-20 13:14:43.331212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1624afc989'
down_revision: Union[str, None] = '353bedcac6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_availabity', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('featured', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('book_rating', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('book_image', sa.String(), nullable=True))
    op.add_column('books', sa.Column('book_audio', sa.String(), nullable=True))
    op.add_column('books', sa.Column('book_pdf', sa.String(), nullable=True))
    op.drop_index('ix_books_isbn', table_name='books')
    op.drop_column('books', 'isbn')
    op.drop_column('books', 'availabity_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('availabity_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_books_isbn', 'books', ['isbn'], unique=True)
    op.drop_column('books', 'book_pdf')
    op.drop_column('books', 'book_audio')
    op.drop_column('books', 'book_image')
    op.drop_column('books', 'book_rating')
    op.drop_column('books', 'featured')
    op.drop_column('books', 'book_availabity')
    # ### end Alembic commands ###
